### 새로운 플랜 생성
POST http://localhost:8080/api/v1/plans
Content-Type: application/json

{
  "name": "밥먹기",
  "description": "아무거나"
}

### 플랜 조회
GET http://localhost:8080/api/v1/plans
Content-Type: application/json

### 플랜 상세 조회
GET http://localhost:8080/api/v1/plans/0
Content-Type: application/json

### 플랜 삭제
DELETE http://localhost:8080/api/v1/plans/14