spring:
  datasource:
    url: jdbc:mysql://localhost:3306/master?useSSL=false&serverTimezone=UTC
    username: kcw
    password: 2122
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect